apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: myapp
    type: docker-2048
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
  